#!/usr/bin/env python

import sys, os
import re

def change_file(tar_file):
	name, ext = os.path.splitext(tar_file)
	flag = 0
	if ext == '.py' or ext == '.pyw':
		os.chmod(tar_file, 0770)
		with open(tar_file, 'r+') as fd:
			data = fd.read()
			xRegex = re.compile(r'^\#!/usr/bin/env\s+python')
			has_x = xRegex.search(data)
			if has_x == None or not has_x.group():
				data = '#!/usr/bin/env python\n' + data
				fd.seek(0, 0)
				fd.write(data)
		
def change_list(tar_dir):
	for i in os.listdir(tar_dir):
		if os.path.isfile(i):
			change_file(i)
#-------------------------------
if len(sys.argv) == 1:
	change_list('.')
else:
	for i in sys.argv[1:]:
		if	os.path.isfile(i):
			change_file(i)
		elif os.path.isdir(i):
			change_list(i)
